# Generated by Django 3.0.5 on 2020-04-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_column='user_id', help_text='User ID number in Telegram', max_length=20, verbose_name='User ID')),
                ('first_name', models.CharField(db_column='first_name', help_text='Contact first Name', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(db_column='last_name', help_text='Contact last name', max_length=50, verbose_name='Last Name')),
                ('phone_number', models.CharField(db_column='phone_number', help_text='Contact phone number', max_length=20, verbose_name='Phone Number')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(db_column='input', help_text='Comand name', verbose_name='Input')),
                ('output', models.TextField(db_column='output', help_text='Output message for user', verbose_name='Output')),
                ('code', models.TextField(db_column='code', help_text='Code or instruction to be execute', verbose_name='Code')),
                ('graph_labels', models.TextField(db_column='graph_labels', help_text='Title and labels for graph', verbose_name='Title and labels')),
            ],
            options={
                'db_table': 'interaction',
            },
        ),
    ]
