# Generated by Django 3.0.5 on 2020-04-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='type',
            field=models.CharField(db_column='type', default='Column', help_text='Graph and Table interation type', max_length=30, verbose_name='Type of interation'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='code',
            field=models.TextField(db_column='code', default='Informar', help_text='Code or instruction to be execute', verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='graph_labels',
            field=models.CharField(db_column='graph_labels', default="title='Informar Título'\nxlabel='Informar Label x'\nylabel='Informar Label y'", help_text='Title and labels for graph', max_length=100, verbose_name='Title and labels'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='input',
            field=models.CharField(db_column='input', default='Informar', help_text='Command name', max_length=50, verbose_name='Input'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='output',
            field=models.CharField(db_column='output', default='Informar', help_text='Output message for user', max_length=50, verbose_name='Output'),
        ),
    ]
