# Generated by Django 3.0.5 on 2020-04-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200424_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='table_labels',
            field=models.TextField(db_column='table_labels', default='Informar', help_text='Title and labels for table', verbose_name='Title and labels'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='graph_labels',
            field=models.TextField(db_column='graph_labels', default="title='Informar Título'\nxlabel='Informar Label x'\nylabel='Informar Label y'", help_text='Title and labels for graph', verbose_name='Title and labels'),
        ),
    ]
